language: node_js
cache:
  directories:
  - node_modules
  - "~/.npm"
node_js:
- 12
git:
  depth: 3
jobs:
  include:
  - stage: lint
    script: npm run lint
  - stage: test
    script: npm run test && npm run coveralls
notifications:
  slack:
    rooms:
      secure: dpW1GC9Ohr4bRObfrVtRCSE2sQSQdSySZmymnPHG757nbgWDdDRom2BBxP6Dj09CchdiECpgX8lj6PCjiQsP27d37x8WcWPMdDAF1PGZdLrhs31IlUQRkg0N/LPU4nQAZdCzgFZ3ki11HkjVIu2dC+PRpnY6fNN2zpWeZpgZAcVfUNVMuBmVep40OQkkY6J8WBUCsHycTynWP3zaNZbGpyD5BMcwyAjyOF8ysA4yaiJwu4O0Vre1Da5ZQ+zKSmtcHbJoMqrSTuheTIl7Ap4uvoEbKhxXpy4eQmBO7Zho/QqcOoKqmZEml1/dvdLhA+XELJLjO9mF7p0POpxYqlCB2RCq47CYX2FLZOceZCCwgvJ93NfPD00JcXihUk02R82deNqDa2+AMJeeYFaqwgQEea0iY6fzgf3042jwr2oRP07GpBXvkEZYzlR/Ksu9hM497A8B16YkoTlLyyTcUEzLy/R3fho6y7OhvTzEM9O2ttGLGtWtRj9rhcqtUxmFw3267PZ62Iaj+WZGWlEtvUbDEmrDGWc7AWXKNylZ0tVfY58gMfSoIBcXG3NX8d1LjzXIZJexZrhO1M4Ei1tJyM3koOIx1iQXbmSNAmdZdn38yybnqNQvdeP2wX+Si3O9PnLVcEDjFC0EzlpXClG7/kifjLQcsvZx30utFMJk8nUEIsc=
  email:
  - viga.23@hotmail.com
  - alver01.12.1990@gmail.com
deploy:
  provider: heroku
  api_key:
    secure: YTSC3UVvxqvnfg1CPLFLwx0fhXi6dOIw11+65EMIsrQuns3mSoz6zm8icduli2P+bahZZ3rx/98u7NMfrfdF5X8zEpTuHkqYnAB2C6I7dAweyrCiP3Ga0FRr0t4AcCyn21XSqSacYjl3enfPGvr+nlywSnsdQcziz/EFINFwcoKmtBiMsk+Qgr5axfU22YodoYFnQjTjIjhC11nIUrJmmO1BfEDA0bQuK1YEUXRiYVW5LkjvvIWHHN4CA7cB2yQFQwC67nAo23DWb4hsKWIVSul0q2/6GLbcNLKRRYlmC2JgS7c20M3onmtACaNfJYZFSkqAL1vaF9/BflA2DtcGDWeD9DhXfuoqtTp5H7z9dUtc3Bh9BjSRXjLRhd7onzeeaOag36E/xByUASQ9/iwZ2p0xKlGuozLg1RI3jE/jfpD93FO3yfAV1LZrWfOVuujvc3PcOus/kjtZeKh0qTNge5JPJL71Mslc/FnnQJnBBb2sL+pGq/EVH4VNW0hk8GciG6w6Eks60M8O+hRQMpV5iumnDafG4r3u5oY3eEJ4WnuSPtZbnFq7ZaG9kDyX4GaEhad63ORFFKL6hDxhlPxqqEBE6T3eOXNGlf//WTqKHHj6n2z/Aq1h1TLJMAtim2bMlhuQqpniWREJUrsb631N47hy3lxmKl6eqUXUiZ4pVos=
  app: api-cafeto
  on:
    repo: Alver23/api-cafeto
