language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
env:
  - AUTH_JWT_EXPIRES=15m
  - AUTH_JWT_SECRET=mySecret
jobs:
  include:
    - stage: lint
      script: "npm run lint"
    - stage: test
      script: "npm run test && npm run coveralls"
